name: MasterDeployCI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Packages
      run: yarn

    - name: Deploy to GH Pages
      run: |
        git config --global user.name 'Vahid Ramezanipour'
        git config --global user.email 'vahidramezanipour@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        yarn deploy